# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^apps/langchain_pinecone_document_chatbot
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
    files: ^apps/langchain_pinecone_document_chatbot

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma
    files: ^apps/langchain_pinecone_document_chatbot

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
    files: ^apps/langchain_pinecone_document_chatbot

- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: bash -c 'cd apps/langchain_pinecone_document_chatbot && poetry run autoflake .'
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
    files: ^apps/langchain_pinecone_document_chatbot

  - id: black
    name: Format with Black
    entry: bash -c 'cd apps/langchain_pinecone_document_chatbot && poetry run black .'
    language: system
    types: [python]
    files: ^apps/langchain_pinecone_document_chatbot

  - id: isort
    name: isort
    entry: bash -c 'cd apps/langchain_pinecone_document_chatbot && poetry run isort .'
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: bash -c 'cd apps/langchain_pinecone_document_chatbot && poetry run flake8 .'
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]

  - id: mypy
    name: Validate types with MyPy
    entry: bash -c 'cd apps/langchain_pinecone_document_chatbot && poetry run mypy .'
    language: system
    types: [python]
    pass_filenames: false
    args:
    - "langchain_pinecone_document_chatbot"
